# Generated by Django 4.1.7 on 2023-03-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_source', models.CharField(max_length=140)),
                ('image_caption', models.CharField(max_length=140)),
            ],
        ),
    ]
