# Generated by Django 4.1.7 on 2023-04-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMA3', '0003_customer_order_delete_part2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=140)),
                ('product_image', models.CharField(max_length=140)),
                ('product_price', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TMA3.product'),
            preserve_default=False,
        ),
    ]
