# Generated by Django 4.1.7 on 2023-04-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMA3', '0004_product_remove_order_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_name', models.CharField(max_length=140)),
                ('cart_product_image', models.CharField(max_length=140)),
                ('cart_product_price', models.CharField(max_length=140)),
            ],
        ),
    ]
