# Generated by Django 4.1.7 on 2023-04-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMA3', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
